// Mapeo de nombres de países a códigos ISO para banderas
export const countryToISO: Record<string, string> = {
  // América
  'Argentina': 'AR',
  'Brasil': 'BR',
  'México': 'MX',
  'Colombia': 'CO',
  'Uruguay': 'UY',
  'Paraguay': 'PY',
  'Chile': 'CL',
  'Perú': 'PE',
  'Ecuador': 'EC',
  'Venezuela': 'VE',
  'Bolivia': 'BO',
  'Panamá': 'PA',
  'Costa Rica': 'CR',
  'Honduras': 'HN',
  'El Salvador': 'SV',
  'Guatemala': 'GT',
  'Nicaragua': 'NI',
  'Jamaica': 'JM',
  'Trinidad y Tobago': 'TT',
  'Estados Unidos': 'US',
  'Canadá': 'CA',
  
  // Europa
  'España': 'ES',
  'Francia': 'FR',
  'Alemania': 'DE',
  'Italia': 'IT',
  'Inglaterra': 'GB',
  'Gales': 'GB',
  'Escocia': 'GB',
  'Irlanda del Norte': 'GB',
  'Portugal': 'PT',
  'Holanda': 'NL',
  'Bélgica': 'BE',
  'Suiza': 'CH',
  'Austria': 'AT',
  'Republica Checa': 'CZ',
  'Dinamarca': 'DK',
  'Suecia': 'SE',
  'Noruega': 'NO',
  'Finlandia': 'FI',
  'Islandia': 'IS',
  'Rumania': 'RO',
  'Polonia': 'PL',
  'Hungría': 'HU',
  'Serbia': 'RS',
  'Croacia': 'HR',
  'eslovenia': 'SI',
  'Ucrania': 'UA',
  'Rusia': 'RU',
  'Grecia': 'GR',
  'Turquía': 'TR',
  'Bosnia': 'BA',
  'Montenegro': 'ME',
  'Albania': 'AL',
  'Bulgaria': 'BG',
  'Eslovaquia': 'SK',
  'Lituania': 'LT',
  'Georgia': 'GE',
  'Armenia': 'AM',
  'Azerbaiyán': 'AZ',
  
  // Asia
  'Japón': 'JP',
  'Corea del Sur': 'KR',
  'China': 'CN',
  'Tailandia': 'TH',
  'Vietnam': 'VN',
  'Malasia': 'MY',
  'Singapur': 'SG',
  'Indonesia': 'ID',
  'Filipinas': 'PH',
  'Irán': 'IR',
  'Irak': 'IQ',
  'Arabia Saudita': 'SA',
  'Emiratos Árabes Unidos': 'AE',
  'Qatar': 'QA',
  'Siria': 'SY',
  'Líbano': 'LB',
  'Israel': 'IL',
  'Jordan': 'JO',
  'Oman': 'OM',
  'Kuwait': 'KW',
  'Uzbekistán': 'UZ',
  'Tayikistán': 'TJ',
  'Kirguistán': 'KG',
  'Kazajstán': 'KZ',
  'Afganistán': 'AF',
  'Paquistán': 'PK',
  'India': 'IN',
  'Bangladesh': 'BD',
  'Nepal': 'NP',
  'Hong Kong': 'HK',
  
  // África
  'Senegal': 'SN',
  'Nigeria': 'NG',
  'Marruecos': 'MA',
  'Egipto': 'EG',
  'Túnez': 'TN',
  'Argelia': 'DZ',
  'Camerún': 'CM',
  'Guinea': 'GN',
  'Costa de Marfil': 'CI',
  'Burkina Faso': 'BF',
  'Mali': 'ML',
  'Benín': 'BJ',
  'Gabón': 'GA',
  'Sudáfrica': 'ZA',
  'Zimbabue': 'ZW',
  'Zambia': 'ZM',
  'Kenia': 'KE',
  'Tanzania': 'TZ',
  'Uganda': 'UG',
  'Etiopía': 'ET',
  'Ghana': 'GH',
  'Liberia': 'LR',
  'Sierra Leona': 'SL',
  'Somalia': 'SO',
  'Sudán': 'SD',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Madagascar': 'MG',
  'Botsuana': 'BW',
  'Lesoto': 'LS',
  'Mozambique': 'MZ',
  'Angola': 'AO',
  'Namibia': 'NA',
  'Malawi': 'MW',
  'Ruanda': 'RW',
  'Burundi': 'BI',
  'Djibouti': 'DJ',
  'Comoras': 'KM',
  'Seychelles': 'SC',
  'Cabo Verde': 'CV',
  'Gambia': 'GM',
  'Guinea Ecuatorial': 'GQ',
  'Santo Tomé y Príncipe': 'ST',
  
  // Oceanía
  'Australia': 'AU',
  'Nueva Zelanda': 'NZ',
  'Fiji': 'FJ',
  'Samoa': 'WS',
  'Islas Salomón': 'SB',
  'Vanuatu': 'VU',
  'Kiribati': 'KI',
  'Palaos': 'PW',
  'Tonga': 'TO',
  'Nauru': 'NR',
  'Tuvalu': 'TV',
  'Islas Marshall': 'MH',
}

export function getCountryISO(countryName?: string): string {
  if (!countryName) return 'UN' // Naciones Unidas por defecto
  
  // Buscar coincidencia exacta
  if (countryToISO[countryName]) {
    return countryToISO[countryName]
  }
  
  // Buscar coincidencia parcial (case-insensitive)
  const normalized = countryName.toLowerCase()
  for (const [country, iso] of Object.entries(countryToISO)) {
    if (country.toLowerCase().includes(normalized) || normalized.includes(country.toLowerCase())) {
      return iso
    }
  }
  
  return 'UN' // Default
}
